# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
    # Set environment 
    config.vm.define "centos_jenkins_dsl" do |cfg|
        cfg.vm.box = "centos/7"
        cfg.vm.box_version = ">=1609.01"
        cfg.vm.provision :shell, path: "bootstrap.sh"
        cfg.vm.network :forwarded_port, guest: 9001, host: 9001
        cfg.vm.synced_folder "../", "/home/vagrant/centos-jenkins-dsl"
        cfg.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", 1048]
            vb.customize ["modifyvm", :id, "--cpus", 1]
        end
    end
end